# -*- coding: utf-8 -*-
"""Helmet-Safety-Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100Xm69SH0GIm3p7zWP12sbNQgesSo29a
"""

from ultralytics import YOLOv10

MODEL_PATH = 'models/yolov10n.pt'
model = YOLOv10(MODEL_PATH)

YAML_PATH = 'safety_helmet_dataset/data.yaml'
EPOCHS = 50
IMG_SIZE = 640
BATCH_SIZE = 32  # 64, 128, 256...

model.train(data=YAML_PATH,
            epochs=EPOCHS,
            batch=BATCH_SIZE,
            imgsz=IMG_SIZE)

TRAINED_MODEL_PATH = 'yolov10/runs/detect/train/weights/best.pt'
model = YOLOv10(TRAINED_MODEL_PATH)

model.val(data=YAML_PATH,
          imgsz=IMG_SIZE,
          split='test')
