# -*- coding: utf-8 -*-
"""yolov10-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUPZmOpk8wxjBK_QEZi1bDbmFpMDX9cP
"""

from ultralytics import YOLOv10

MODEL_PATH = 'yolov10/yolov10n.pt'
model = YOLOv10(MODEL_PATH)

IMG_PATH = 'images/HCMC_Street.jpg'
result = model(source=IMG_PATH)[0]

result.save('images/HCMC_Street_predict.png')
